### ISSUE TITLE
Placeholder Variables

### ISSUE THREAD

**Issue by stephenway** [hagenburger/compass-placeholders#2]
They don't seem to work right now.

[https://gist.github.com/stephenway/7346599](https://gist.github.com/stephenway/7346599)

**Comment by stephenway** [comment]
Ok looks like my bad, although documentation could be improved to show how to do this out of the box.

``` scss
$border-radius-placeholder: none, 5px;

@import "compass";
@import "compass-placeholders";

#test-1 {
    @extend %border-radius-none;
}
```

I was putting the var below the import, once I switched them it started working. However I'm surprised it didn't work the other way around.
